### ISSUE TITLE
Stays on installing in node-red 3.0.0

### ISSUE THREAD

**Issue by hipitihop** [ntsaini/node-red-contrib-function-npm#49]
I recently switched to node-red 3.0.0 and now my function-npm nodes stay on "installing" indefinitely. Any messages that come into to the flow, just fall on the floor. The flow and function-npm nodes worked perfectly previously. This obviously could be something NR 3.0.0 has caused and not this node specifically, but thought I would report.

![image](https://user-images.githubusercontent.com/4626024/181157726-df1d6b15-9d12-4345-86a7-678893a83b27.png)

**Comment by bisand** [comment]
I am also experiencing this. Could it be related to Node-RED 3.0.0 have been upgraded to use Node.js 16 and NPM >= 8.0.0 and therefore no more access to the programmatic API?!

See strack trace from the Node-RED log file:
```
/data/node_modules/global-npm/index.js:37
 throw e
 ^

Error: The programmatic API was removed in npm v8.0.0
 at Object.<anonymous> (/usr/local/lib/node_modules/npm/index.js:4:9)
 at Module._compile (node:internal/modules/cjs/loader:1105:14)
 at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
 at Module.load (node:internal/modules/cjs/loader:981:32)
 at Function.Module._load (node:internal/modules/cjs/loader:822:12)
 at Module.require (node:internal/modules/cjs/loader:1005:19)
 at require (node:internal/modules/cjs/helpers:102:18)
 at /data/node_modules/global-npm/index.js:29:15
 at Object.<anonymous> (/data/node_modules/global-npm/index.js:41:3)
 at Module._compile (node:internal/modules/cjs/loader:1105:14)
/data/node_modules/global-npm/index.js:37
 throw e
 ^

Error: The programmatic API was removed in npm v8.0.0
 at Object.<anonymous> (/usr/local/lib/node_modules/npm/index.js:4:9)
 at Module._compile (node:internal/modules/cjs/loader:1105:14)
 at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
 at Module.load (node:internal/modules/cjs/loader:981:32)
 at Function.Module._load (node:internal/modules/cjs/loader:822:12)
 at Module.require (node:internal/modules/cjs/loader:1005:19)
 at require (node:internal/modules/cjs/helpers:102:18)
 at /data/node_modules/global-npm/index.js:29:15
 at Object.<anonymous> (/data/node_modules/global-npm/index.js:41:3)
 at Module._compile (node:internal/modules/cjs/loader:1105:14)

```
Also see this issue: https://github.com/raine/npm-install-to/issues/1

**Comment by xuptlee** [comment]
I‘m also get this question. but my :
node-red version : v2.1.4
node.js version : v14.18.2
npm version : v8.5.5
I don't know how to resolve. Maybe I should replace lower npm version?

**Comment by ntsaini** [comment]
It is certainly possible that the removal of programmatic API is causing this issue. The codebase was rewritten to use [npm-install-to](https://github.com/raine/npm-install-to) instead of directly calling programmatic apis in this code but if that package is affected it will cause problems in this one too. 

Seems like the common thread between the issues is the npm version > 8.0. If npm has truly disabled programmatic access nothing much can be done unless their is an alternate way. I am open to suggestions, currently I am relying on [npm-install-to](https://github.com/raine/npm-install-to) so easier if the change is made there but open to writing the alternate method directly in the codebase. 

Feel free to send a pull request, if you have any suggestions. In the meanwhile, I suggest you downgrade npm version below 8.0

**Comment by xuptlee** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hipitihop** [comment]
For the benefit of others, I have found a workaround, using native NR support.
See details here: https://github.com/node-red/node-red/issues/3803#issuecomment-1279617830
Closing
